#ifndef _INCLUDED_poissongroup_2_spike_thresholder_codeobject_after
#define _INCLUDED_poissongroup_2_spike_thresholder_codeobject_after

void _after_run_poissongroup_2_spike_thresholder_codeobject();

#endif
