#ifndef _INCLUDED_IAMPA_TC_RE_summed_variable_iAMPA_TC_RE_post_codeobject
#define _INCLUDED_IAMPA_TC_RE_summed_variable_iAMPA_TC_RE_post_codeobject

void _run_IAMPA_TC_RE_summed_variable_iAMPA_TC_RE_post_codeobject();


#endif
