#ifndef _INCLUDED_IAMPA_PYso_PYdr_synapses_create_array_codeobject
#define _INCLUDED_IAMPA_PYso_PYdr_synapses_create_array_codeobject

void _run_IAMPA_PYso_PYdr_synapses_create_array_codeobject();


#endif
