#ifndef _INCLUDED_IAMPA_TC_IN_summed_variable_iAMPA_TC_IN_post_codeobject
#define _INCLUDED_IAMPA_TC_IN_summed_variable_iAMPA_TC_IN_post_codeobject

void _run_IAMPA_TC_IN_summed_variable_iAMPA_TC_IN_post_codeobject();


#endif
