#ifndef _INCLUDED_ICOM_PYso_PYdr_synapses_create_generator_codeobject
#define _INCLUDED_ICOM_PYso_PYdr_synapses_create_generator_codeobject

void _run_ICOM_PYso_PYdr_synapses_create_generator_codeobject();


#endif
