#ifndef _INCLUDED_IGABAA_RE_RE_synapses_create_generator_codeobject
#define _INCLUDED_IGABAA_RE_RE_synapses_create_generator_codeobject

void _run_IGABAA_RE_RE_synapses_create_generator_codeobject();


#endif
