#include<stdlib.h>
#include "objects.h"
#include<ctime>
#include<random>

#include "code_objects/IAMPA_PYso_IN_down_codeobject.h"
#include "code_objects/IAMPA_PYso_IN_down_push_spikes.h"
#include "code_objects/IAMPA_PYso_IN_stateupdater_codeobject.h"
#include "code_objects/IAMPA_PYso_IN_summed_variable_iAMPA_PYso_IN_post_codeobject.h"
#include "code_objects/IAMPA_PYso_IN_synapses_create_array_codeobject.h"
#include "code_objects/IAMPA_PYso_IN_up_codeobject.h"
#include "code_objects/IAMPA_PYso_IN_up_push_spikes.h"
#include "code_objects/IAMPA_PYso_PYdr_down_codeobject.h"
#include "code_objects/IAMPA_PYso_PYdr_down_push_spikes.h"
#include "code_objects/IAMPA_PYso_PYdr_stateupdater_codeobject.h"
#include "code_objects/IAMPA_PYso_PYdr_summed_variable_iAMPA_PYso_PYdr_post_codeobject.h"
#include "code_objects/IAMPA_PYso_PYdr_synapses_create_array_codeobject.h"
#include "code_objects/IAMPA_PYso_PYdr_up_codeobject.h"
#include "code_objects/IAMPA_PYso_PYdr_up_push_spikes.h"
#include "code_objects/IAMPA_PYso_RE_stateupdater_codeobject.h"
#include "code_objects/IAMPA_PYso_RE_summed_variable_iAMPA_PYso_RE_post_codeobject.h"
#include "code_objects/IAMPA_PYso_RE_synapses_create_array_codeobject.h"
#include "code_objects/IAMPA_PYso_TC_stateupdater_codeobject.h"
#include "code_objects/IAMPA_PYso_TC_summed_variable_iAMPA_PYso_TC_post_codeobject.h"
#include "code_objects/IAMPA_PYso_TC_synapses_create_array_codeobject.h"
#include "code_objects/IAMPA_TC_IN_stateupdater_codeobject.h"
#include "code_objects/IAMPA_TC_IN_summed_variable_iAMPA_TC_IN_post_codeobject.h"
#include "code_objects/IAMPA_TC_IN_synapses_create_array_codeobject.h"
#include "code_objects/IAMPA_TC_PYdr_stateupdater_codeobject.h"
#include "code_objects/IAMPA_TC_PYdr_summed_variable_iAMPA_TC_PYdr_post_codeobject.h"
#include "code_objects/IAMPA_TC_PYdr_synapses_create_array_codeobject.h"
#include "code_objects/IAMPA_TC_RE_stateupdater_codeobject.h"
#include "code_objects/IAMPA_TC_RE_summed_variable_iAMPA_TC_RE_post_codeobject.h"
#include "code_objects/IAMPA_TC_RE_synapses_create_generator_codeobject.h"
#include "code_objects/ICOM_PYdr_PYso_summed_variable_iCOM_post_codeobject.h"
#include "code_objects/ICOM_PYdr_PYso_synapses_create_generator_codeobject.h"
#include "code_objects/ICOM_PYso_PYdr_summed_variable_iCOM_post_codeobject.h"
#include "code_objects/ICOM_PYso_PYdr_synapses_create_generator_codeobject.h"
#include "code_objects/IGABAA_IN_IN_down_codeobject.h"
#include "code_objects/IGABAA_IN_IN_down_push_spikes.h"
#include "code_objects/IGABAA_IN_IN_stateupdater_codeobject.h"
#include "code_objects/IGABAA_IN_IN_summed_variable_iGABAA_IN_IN_post_codeobject.h"
#include "code_objects/IGABAA_IN_IN_synapses_create_array_codeobject.h"
#include "code_objects/IGABAA_IN_IN_up_codeobject.h"
#include "code_objects/IGABAA_IN_IN_up_push_spikes.h"
#include "code_objects/IGABAA_IN_PYso_down_codeobject.h"
#include "code_objects/IGABAA_IN_PYso_down_push_spikes.h"
#include "code_objects/IGABAA_IN_PYso_stateupdater_codeobject.h"
#include "code_objects/IGABAA_IN_PYso_summed_variable_iGABAA_IN_PYso_post_codeobject.h"
#include "code_objects/IGABAA_IN_PYso_synapses_create_array_codeobject.h"
#include "code_objects/IGABAA_IN_PYso_up_codeobject.h"
#include "code_objects/IGABAA_IN_PYso_up_push_spikes.h"
#include "code_objects/IGABAA_RE_RE_stateupdater_codeobject.h"
#include "code_objects/IGABAA_RE_RE_summed_variable_iGABAA_RE_RE_post_codeobject.h"
#include "code_objects/IGABAA_RE_RE_synapses_create_generator_codeobject.h"
#include "code_objects/IGABAA_RE_TC_stateupdater_codeobject.h"
#include "code_objects/IGABAA_RE_TC_summed_variable_iGABAA_RE_TC_post_codeobject.h"
#include "code_objects/IGABAA_RE_TC_synapses_create_generator_codeobject.h"
#include "code_objects/IGABAB_RE_TC_stateupdater_codeobject.h"
#include "code_objects/IGABAB_RE_TC_summed_variable_iGABAB_RE_TC_post_codeobject.h"
#include "code_objects/IGABAB_RE_TC_synapses_create_generator_codeobject.h"
#include "code_objects/IKNa_PYso_PYdr_stateupdater_codeobject.h"
#include "code_objects/IKNa_PYso_PYdr_summed_variable_iKNa_post_codeobject.h"
#include "code_objects/IKNa_PYso_PYdr_synapses_create_generator_codeobject.h"
#include "code_objects/IN_group_spike_resetter_codeobject.h"
#include "code_objects/IN_group_spike_thresholder_codeobject.h"
#include "code_objects/IN_group_stateupdater_codeobject.h"
#include "code_objects/IN_spikemon_codeobject.h"
#include "code_objects/INMDA_PYso_IN_down_codeobject.h"
#include "code_objects/INMDA_PYso_IN_down_push_spikes.h"
#include "code_objects/INMDA_PYso_IN_stateupdater_codeobject.h"
#include "code_objects/INMDA_PYso_IN_summed_variable_iNMDA_PYso_IN_post_codeobject.h"
#include "code_objects/INMDA_PYso_IN_synapses_create_array_codeobject.h"
#include "code_objects/INMDA_PYso_IN_up_codeobject.h"
#include "code_objects/INMDA_PYso_IN_up_push_spikes.h"
#include "code_objects/INMDA_PYso_PYdr_down_codeobject.h"
#include "code_objects/INMDA_PYso_PYdr_down_push_spikes.h"
#include "code_objects/INMDA_PYso_PYdr_stateupdater_codeobject.h"
#include "code_objects/INMDA_PYso_PYdr_summed_variable_iNMDA_PYso_PYdr_post_codeobject.h"
#include "code_objects/INMDA_PYso_PYdr_synapses_create_array_codeobject.h"
#include "code_objects/INMDA_PYso_PYdr_up_codeobject.h"
#include "code_objects/INMDA_PYso_PYdr_up_push_spikes.h"
#include "code_objects/poissongroup_1_spike_thresholder_codeobject.h"
#include "code_objects/poissongroup_2_spike_thresholder_codeobject.h"
#include "code_objects/poissongroup_spike_thresholder_codeobject.h"
#include "code_objects/PYdr_group_spike_resetter_codeobject.h"
#include "code_objects/PYdr_group_spike_thresholder_codeobject.h"
#include "code_objects/PYdr_group_stateupdater_codeobject.h"
#include "code_objects/PYdr_spikemon_codeobject.h"
#include "code_objects/PYso_group_spike_resetter_codeobject.h"
#include "code_objects/PYso_group_spike_thresholder_codeobject.h"
#include "code_objects/PYso_group_stateupdater_codeobject.h"
#include "code_objects/PYso_spikemon_codeobject.h"
#include "code_objects/RE_group_spike_resetter_codeobject.h"
#include "code_objects/RE_group_spike_thresholder_codeobject.h"
#include "code_objects/RE_group_stateupdater_codeobject.h"
#include "code_objects/RE_spikemon_codeobject.h"
#include "code_objects/synapses_1_pre_codeobject.h"
#include "code_objects/synapses_1_pre_push_spikes.h"
#include "code_objects/synapses_1_synapses_create_generator_codeobject.h"
#include "code_objects/synapses_2_pre_codeobject.h"
#include "code_objects/synapses_2_pre_push_spikes.h"
#include "code_objects/synapses_2_synapses_create_generator_codeobject.h"
#include "code_objects/synapses_pre_codeobject.h"
#include "code_objects/synapses_pre_push_spikes.h"
#include "code_objects/synapses_synapses_create_generator_codeobject.h"
#include "code_objects/TC_group_spike_resetter_codeobject.h"
#include "code_objects/TC_group_spike_thresholder_codeobject.h"
#include "code_objects/TC_group_stateupdater_codeobject.h"
#include "code_objects/TC_group_subexpression_update_codeobject.h"
#include "code_objects/TC_spikemon_codeobject.h"


void brian_start()
{
	_init_arrays();
	_load_arrays();
	// Initialize clocks (link timestep and dt to the respective arrays)
    brian::defaultclock.timestep = brian::_array_defaultclock_timestep;
    brian::defaultclock.t = brian::_array_defaultclock_t;
    brian::defaultclock.dt = brian::_array_defaultclock_dt;
}

void brian_end()
{
	_write_arrays();
	_dealloc_arrays();
}


